{
  "hash": "0fb736d4a8d4211c002731a542997d9f",
  "result": {
    "engine": "knitr",
    "markdown": "# Distribuições de Probabilidade {#sec-distribuicoes}\n\nDistribuições teóricas são modelos matemáticos que descrevem como os dados se comportam. Elas são importantes porque permitem a modelagem e previsão de fenômenos naturais, fazendo inferências sobre uma população a partir de uma amostra e testando hipóteses para determinar a significância dos resultados observados.\n\nPacotes usados neste capítulo, carregados uma única vez no início, como recomendado no capítulo sobre pacotes (@sec-packages):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n```\n:::\n\n\nNa medicina, esses conceitos são aplicados de várias maneiras. Ensaios clínicos utilizam distribuições teóricas para determinar a significância dos resultados dos testes de tratamento, por exemplo, modelando a distribuição dos resultados com a distribuição normal. Estudos epidemiológicos usam distribuições para modelar a incidência e prevalência de doenças, como a distribuição de Poisson para modelar o número de novos casos em um determinado período. A análise de sobrevivência utiliza a distribuição exponencial para modelar o tempo de sobrevivência dos pacientes após um tratamento ou o tempo até a ocorrência de um evento específico, como a recaída de uma doença. Distribuições teóricas de probabilidade são, portanto, elementos fundamentais da análise estatística.\n\nO R, sendo uma linguagem estatística, naturalmente possui diversos comandos para criar conjuntos de números aleatórios com distribuições de diversos tipos. Para cada distribuição o R possui 4 funções principais: densidade de probabilidade (d), probabilidade cumulativa (p), quantis (q) e números randomizados (r). Cada uma dessas funções é obtida colocando-se a letra correspondente (d, p, q, r) como prefixo do nome da distribuição no R. A tabela abaixo mostra algumas das distribuições e as funções associadas.\n\n![](images/distributions_table.png)\n\n## Definindo o ponto de partida para a geração de números aleatórios\n\nA função `set.seed()` do R é utilizada para definir a semente (ou seed, em inglês) de geração de números aleatórios, ou seja, o ponto de partida para a geração de números aleatórios. Isso é particularmente útil quando você precisa garantir que seus resultados sejam reprodutíveis. Ao definir uma semente específica, qualquer operação subsequente que envolva a geração de números aleatórios produzirá os mesmos resultados em diferentes execuções, desde que a mesma semente seja usada.\n\nSem definir uma semente, os resultados da simulação mudarão a cada execução. No entanto, ao usar `set.seed()`, você pode garantir que os resultados sejam consistentes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cada execução desse código resultará em uma sequência diferente de 5 números.\nrnorm(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  0.1872419  0.5319381 -0.3295648 -0.5209226 -0.2732500\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cada execução desse código resultará sempre na mesma sequência de 5 números.\n# Alterar o argumento da função set.seed irá mudar a sequência de números.\nset.seed(1)\nrnorm(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.6264538  0.1836433 -0.8356286  1.5952808  0.3295078\n```\n\n\n:::\n:::\n\n\nA semente deve ser sempre um número inteiro. Diferentes números de sementes levarão a diferentes sequências de números aleatórios. Observe que `set.seed()` não altera os números gerados globalmente para toda a sessão R, mas garante que a sequência de números aleatórios gerados após definir a semente seja a mesma.\n\n## Distribuição Uniforme\n\n### `runif`\n\nA função `runif()` gera um conjunto randomizado de números a partir de uma distribuição uniforme. Os argumentos dessa função são: a quantidade de números, o valor mínimo e o valor máximo.\n\nVeja abaixo como criar um conjunto randomizado de 20 números distribuídos de forma uniforme entre 0 e 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nru1 <- runif(n = 20, min = 0, max = 1)\nru1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 0.20597457 0.17655675 0.68702285 0.38410372 0.76984142 0.49769924\n [7] 0.71761851 0.99190609 0.38003518 0.77744522 0.93470523 0.21214252\n[13] 0.65167377 0.12555510 0.26722067 0.38611409 0.01339033 0.38238796\n[19] 0.86969085 0.34034900\n```\n\n\n:::\n:::\n\n\npodemos arredondar esses valores com a função round().\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# arredondando para 2 casas decimais\nround(ru1, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 0.21 0.18 0.69 0.38 0.77 0.50 0.72 0.99 0.38 0.78 0.93 0.21 0.65 0.13 0.27\n[16] 0.39 0.01 0.38 0.87 0.34\n```\n\n\n:::\n:::\n\n\nPodemos visualizar um histograma dessa distribuição com a função `hist()`. Veja que com poucos elementos a distribuição ainda não parece uniforme.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(ru1)\n```\n\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nEntretanto, à medida que aumentamos o número de elementos, a forma da distribuição se parece cada vez mais com uma distribuição uniforme. Veja no código abaixo um conjunto randomizado de 10, 100, 1000 e 10.000 elementos criados com a função `runif(`) e os histogramas dessas distribuições.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nru1 <- runif(n = 10, min = 0, max = 1)\nru2 <- runif(n = 100, min = 0, max = 1)\nru3 <- runif(n = 1000, min = 0, max = 1)\nru4 <- runif(n = 10000, min = 0, max = 1)\npar(mfrow = c(2, 2)) # cria uma matrix 2x2 para plotar os gráficos\nhist(ru1)\nhist(ru2)\nhist(ru3)\nhist(ru4)\n```\n\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n### `dunif`\n\nA função `dunif()` calcula a função de densidade de probabilidade (PDF) da distribuição uniforme. Atenção: numa distribuição contínua, a probabilidade de a variável ser exatamente igual a um valor é zero; a densidade mede o quanto a probabilidade se concentra em torno daquele valor, e é a área sob a curva de densidade (calculada por `punif()`, logo abaixo) que dá probabilidades. A função `dunif()` tem três argumentos:\n\n-   x: o valor no qual calcular o PDF\n-   min: o limite inferior da distribuição\n-   max: o limite superior da distribuição\n\nVeja como usar a função `dunif()` para calcular o PDF de uma distribuição uniforme entre 0 e 100 no valor 5:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndunif(x=5, min=0, max=100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01\n```\n\n\n:::\n:::\n\n\nA densidade é 0.01 em qualquer ponto entre 0 e 100, porque na distribuição uniforme ela é constante e igual a 1/(max − min) = 1/100. Como consequência, a probabilidade de a variável cair num intervalo qualquer é o comprimento do intervalo vezes 0.01: por exemplo, entre 5 e 15 é 0.10.\n\n### `punif`\n\nA função `punif()` calcula a função de densidade de probabilidade cumulativa (CDF) da distribuição uniforme, ou seja, a probabilidade de que uma variável aleatória seja menor ou igual a um determinado valor.\n\nA função `punif()` requer três argumentos:\n\n-   x: o valor no qual calcular o CDF\\\n-   min: o limite inferior da distribuição\\\n-   max: o limite superior da distribuição\n\nVeja um exemplo de como usar a função `punif()` para calcular o CDF de uma distribuição uniforme entre 0 e 100 no valor 5:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npunif(5, min = 0, max = 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05\n```\n\n\n:::\n:::\n\n\n### `qunif`\n\nA função `qunif()` calcula a função quantil da distribuição uniforme. A função quantil é o inverso do CDF. Dada uma probabilidade como entrada, a função retorna o valor que tem essa probabilidade.\n\nA função `qunif()` requer três argumentos:\n\n-   p: a probabilidade\\\n-   min: o limite inferior da distribuição\\\n-   max: o limite superior da distribuição\n\nVeja exemplo de como usar a função `qunif()` para calcular o quantil de uma distribuição uniforme entre 0 e 100 na probabilidade de 0.05:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqunif(0.05, min = 0, max = 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5\n```\n\n\n:::\n:::\n\n\n## Distribuição Normal\n\nA mais importante das distribuições de probabilidade teóricas é a distribuição normal. Diversos fenômenos na natureza seguem um padrão de distribuição simétrico e em forma de sino. Devido a essa forma, essa distribuição de frequências ficou conhecida como distribuição em sino (bell shaped). Como tantos fenômenos são distribuídos dessa forma, a busca por um modelo matemático para modelar essa distribuição tem uma longa e interessante trajetória na ciência, envolvendo diversos grandes matemáticos. O modelo matemático dessa curva começou a ser construído por volta do ano de 1733 com o trabalho do matemático Abraham Demoivre, quando buscava modelos para prever resultados de jogos de azar e em 1786 por Pierre Laplace, um astrônomo e matemático. No entanto, a curva normal como modelo para a distribuição de erros na teoria científica é mais comumente associada a um astrônomo e matemático alemão, Karl Friedrich Gauss, que encontrou uma nova derivação da fórmula para a curva em 1809 [@gordon2006normal]. Por esse motivo, a curva normal às vezes é referida como a curva \"Gaussiana\". Em 1835, outro matemático e astrônomo, Lambert Quetelet, usou o modelo para descrever características fisiológicas e sociais humanas. Quetelet acreditava que \"normal\" significava média e que os desvios da média eram os erros da natureza. Apesar da visão distorcida de Quetelet, ele foi o primeiro matemático a estender o uso da curva de distribuição normal para os campos das ciências sociais e biomédicas [@stahl2006evolution].\n\n### `rnorm`\n\nA função `rnorm()` gera um conjunto de números randomizados a partir de uma distribuição normal. Os argumentos dessa função são: a quantidade de números, a média e o desvio padrão. Se introduzirmos apenas a quantidade de números, a função `rnorm()` utiliza a distribuição normal padrão, com média = 0 e desvio padrão = 1.\n\nGerando um conjunto randomizado de 1000 números distribuídos de forma normal com média = 0 e desvio padrão = 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100)\nrn1 <- rnorm(n = 1000, mean = 0, sd = 1)\nplot(density(rn1)) \n```\n\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nPoderíamos também escrever a função acima com os argumentos pela ordem:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(100)\nrn1 <- rnorm(1000, 0, 1)\nplot(density(rn1)) \n```\n\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Inserindo apenas o número de valores a serem gerados\n# Nesse caso a função rnorm usa os valores default para media e desvio padrão\n# media = 0 e desvio padrão = 1 (curva normal padrão)\nset.seed(100)\nrn1 <- rnorm(1000)\nplot(density(rn1)) \n```\n\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n### `dnorm`\n\nA função `dnorm()` é a função de densidade de probabilidade (PDF) de uma distribuição normal e retorna o valor da densidade de probabilidade de um valor x, ou seja, a altura da curva normal naquele ponto. Tem como argumentos o valor x e a média e o desvio padrão da curva. O primeiro argumento é o ponto no eixo x do qual se pretende saber o valor da densidade de probabilidade, o segundo argumento é a média e o terceiro argumento é o desvio padrão.\n\nPor exemplo, para saber o valor da densidade de probabilidade de x=2, numa curva normal padrão (média =0 e desvio padrão =1), o código seria:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndnorm(2, mean = 0, sd = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05399097\n```\n\n\n:::\n:::\n\n\nNuma curva normal padrão não precisamos informar os valores da média e do desvio padrão, bastando inserir o ponto do eixo x.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndnorm(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05399097\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nA função `dnorm(x)` pode ser usada também para gerar todos os pontos da curva normal. Isso pode ser útil para desenhar gráficos da curva normal com códigos bem curtos, quando a associamos à função `curve()`, como mostrado nos códigos abaixo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve(dnorm(x), -3, 3)\n```\n\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve(dnorm(x, mean = 10, sd = 2), 4, 16)\n```\n\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve(dnorm(x, mean= 100, sd= 10), 50, 150)\n```\n\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nPodemos inserir várias curvas num mesmo gráfico com o argumento `add=TRUE`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve(dnorm(x, sd=1), col=\"black\", xlim=c(-10,10), ylim=c(0,0.4), ylab=\"Densidade\")\ncurve(dnorm(x, sd=2), col=\"brown\", xlim=c(-10,10), ylim=c(0,0.4), ylab=\"Densidade\", add=TRUE)\ncurve(dnorm(x, sd=3), col=\"blue\",  xlim=c(-10,10), ylim=c(0,0.4), ylab=\"Densidade\", add=TRUE)\ncurve(dnorm(x, sd=4), col=\"red\",   xlim=c(-10,10), ylim=c(0,0.4), ylab=\"Densidade\", add=TRUE)\ncurve(dnorm(x, sd=5), col=\"green\", xlim=c(-10,10), ylim=c(0,0.4), ylab=\"Densidade\", add=TRUE)\nlegend(x = 2.4, y = 0.41, lty=1, \nlegend = c(\"σ = 1\",   \"σ = 2\",   \"σ = 3\",  \"σ = 4\",  \"σ = 5\"),\ncol =    c(\"black\",   \"brown\",   \"blue\",   \"red\",    \"green\"))\n```\n\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n### `pnorm`\n\nA função `pnorm(x)` é utilizada para calcular a função de distribuição acumulada (CDF) de uma distribuição normal. Em outras palavras, ela fornece a probabilidade de que uma variável aleatória com distribuição normal padrão seja menor ou igual a um determinado valor x. Do ponto de vista gráfico, essa função calcula área abaixo da curva normal, à esquerda de x, ou seja, a probabilidade de dados menores que x. O gráfico abaixo mostra a interpretação visual da função `pnorm(x)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculando pnorm de x=2 na curva normal padrão\npnorm(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9772499\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nObserve que a função `pnorm(x)` usou os valores padrões de média = 0 e desvio padrão = 1. Caso seja necessário usar outros valores, basta inserir esses argumentos na função pnorm().\n\nVamos usar um estudo da ANAC (Agência Nacional de Aviação Civil) [@Silva2009] como exemplo. Nesse estudo a média da altura dos homens brasileiros usuários do sistema de aviação foi estimada em 173,1 cm com um desvio padrão de 7,3cm. Usando esses dados como exemplo, podemos calcular qual o percentual de homens dessa amostra com altura inferior a 190cm.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(190, mean=173.1, sd=7.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9896954\n```\n\n\n:::\n:::\n\n\nA função `pnorm(x)` calcula a área abaixo da curva À ESQUERDA do ponto x. Como a área total abaixo de uma curva normal é 1, para saber a área à direita basta subtrair o resultado de 1, como feito abaixo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pnorm(190, mean=173.1, sd=7.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01030459\n```\n\n\n:::\n:::\n\n\nOu seja, aproximadamente 1% dos homens brasileiros dessa amostra têm altura superior a 190cm.\f\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n### `qnorm`\n\nA função `qnorm()` faz o cálculo inverso da função `pnorm()`. É utilizada para calcular o quantil (ou percentil) de uma distribuição normal. Isso significa que ela fornece o valor x tal que a área sob a curva normal à esquerda de x é igual a uma probabilidade especificada p. O argumento da função `qnorm(p)` é exatamente essa probabilidade, o percentual abaixo da curva à esquerda do ponto x. O resultado dessa função é o valor no eixo x que delimita essa área.\n\nCom essa função podemos nos perguntar qual deve ser a altura das portas de um avião para que 99% dos brasileiros usuários dos aeroportos possam passar pela porta de um avião sem ter de se abaixar? Ou seja, qual a medida da estatura abaixo da qual estão 99% dos brasileiros dessa amostra? Lembrando que a média da altura dos homens brasileiros usuários do sistema de aviação foi estimada em 173,1 cm com um desvio padrão de 7,3cm, o código fica assim:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.99, mean=173.1, sd=7.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 190.0823\n```\n\n\n:::\n:::\n\n\nEssa análise pode ser visualizada no gráfico abaixo:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n## Distribuição t de Student\n\nA distribuição t de Student (também conhecida como distribuição t) foi introduzida por William Sealy Gosset em 1908, sendo usada para estimar a média de variáveis aleatórias normalmente distribuídas para as quais o tamanho da amostra é pequeno e o desvio padrão é desconhecido. A distribuição t parece muito semelhante à distribuição normal, e converge para a curva normal à medida que o tamanho da amostra aumenta.\n\n### `rt()`\n\nA função `rt()` cria conjunto randomizado de números a partir de uma distribuição t de Student. Os argumentos dessa função são: a quantidade de números e os graus de liberdade (*degrees of freedom* - df).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nx <- rt(n = 1000, df = 10)\nplot(density(x))\n```\n\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n### `dt()`\n\nAs funções `dt()`, `pt()`, `qt()` funcionam da mesma forma que suas correspondentes na distribuição normal, como já discutido anteriormente, com a diferença de que o parâmetro da distribuição t são os graus de liberdade (degrees of freedom - df) e não a média e o desvio padrão.\n\nA função `dt()` é a função de densidade de probabilidade (PDF) na curva de distribuição t. Tem como argumento o ponto no eixo x e os graus de liberdade e seu resultado é o valor da densidade de probabilidade, ou a altura da curva t nesse ponto.\n\nPor exemplo, para saber o valor da densidade de probabilidade de x=2, numa curva de distribuição t com 5 graus de liberdade (df = 5), o código seria:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndt(x=2, df=5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.06509031\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nA função `dt()` pode ser usada também para gerar todos os pontos da curva, o que pode ser útil para desenhar gráficos da curva t com códigos bem curtos, quando a associamos à função `curve()`, como mostrado nos códigos abaixo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve(dt(x, df = 5), \n      xlim = c(-4,4) )\n```\n\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nPodemos inserir várias curvas num mesmo gráfico, usando o argumento add=TRUE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve(dnorm(x),   col=\"black\", xlim=c(-5,5), ylim=c(0,0.4), ylab=\"Densidade\")\ncurve(dt(x,df=20),col=\"brown\", add=TRUE)\ncurve(dt(x,df=5), col=\"blue\",  add=TRUE)\ncurve(dt(x,df=2), col=\"red\",   add=TRUE)\ncurve(dt(x,df=1), col=\"green\", add=TRUE)\nlegend(x = 2.4, y = 0.41, lty=1, \nlegend = c(\"normal curve\",\"t, df=20\",\"t, df=5\",\"t, df=2\",\"t, df=1\"),\ncol =    c(       \"black\",   \"brown\",   \"blue\",    \"red\",  \"green\"))\n```\n\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n### `pt()`\n\nA função `pt(q)` é utilizada para calcular a função de distribuição acumulada (CDF) da distribuição t de Student. Ela fornece a probabilidade de que uma variável aleatória com uma distribuição t de Student seja menor ou igual a um determinado valor x. Ou seja, calcula área abaixo da curva de distribuição t, à esquerda de q (quantil).\n\nOs argumentos dessa função são o quantil (q) e os graus de liberdade da curva t (df). O código e o gráfico abaixo mostram o resultado da função `pt()` e a interpretação visual da função.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npt(q = 2, df = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9490303\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n### `qt()`\n\nA função `qt()`, faz o inverso da função `pt()`: dada uma área abaixo da curva de distribuição t, a função retorna o quantil (q) que delimita essa área à esquerda. Os argumentos dessa função são a área em decimais (p) e os graus de liberdade da curva t (df). O resultado da função é o quantil.\n\nComo exemplo, usamos a probabilidade 0.9490303, que é justamente o resultado de `pt(q = 2, df = 5)` calculado acima. A função devolve então o quantil 2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqt(p = 0.9490303, df = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.000001\n```\n\n\n:::\n:::\n\n\n## Distribuição Chi-quadrado\n\nA distribuição qui-quadrado é frequentemente usada em testes estatísticos, como o teste de independência em tabelas de contingência ou o teste de ajuste (goodness-of-fit).\n\n### `rchisq()`\n\nA função `rchisq()` cria conjunto randomizado de números a partir de uma distribuição Chi quadrado. Os argumentos dessa função são: a quantidade de números e os graus de liberdade (degrees of freedom - df).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\ny <- rchisq(n = 1000, df = 3)\nplot(density(y))\n```\n\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n### `dchisq()`\n\nA função `dchisq()` é utilizada para calcular a função densidade de probabilidade (PDF) de uma distribuição qui-quadrado ($\\chi^2$). Ela retorna a densidade da função qui-quadrado para um dado valor x, ou seja, a altura da curva de densidade qui-quadrado naquele ponto específico.\n\nPodemos usar a função `dchisq()` para construir gráficos da distribuição chi-quadrado, da mesma forma como fizemos com a curva normal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve(dchisq(x, df=3), \n      col=\"black\",\n      xlim=c(0,30), \n      ylim=c(0,0.6),\n      ylab=\"Chi Square Density\")\n```\n\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\nE também podemos usar o argumento add=TRUE para inserir várias curvas no mesmo gráfico.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve(dchisq(x, df=1 ),col=\"black\", xlim=c(0,30), ylim=c(0,0.6), ylab=\"Chi Square Density\")\ncurve(dchisq(x, df=2 ),col=\"red\",         add=TRUE)\ncurve(dchisq(x, df=3 ),col=\"blue\",        add=TRUE)\ncurve(dchisq(x, df=5 ),col=\"dark green\",  add=TRUE)\ncurve(dchisq(x, df=10),col=\"brown\",       add=TRUE)\nlegend(x = 25, y = 0.55, \n       legend = c(\"df=1\",\"df=2\",\"df=3\",\"df=5\",\"df=10\"),\n       col    = c(\"black\",\"red\",\"blue\",\"dark green\",\"brown\"),\n       lty=1)\n```\n\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\nAs funções `pchisq()`, `qchisq()` funcionam da mesma forma que suas correspondentes na distribuição normal e t de Student, como já discutido anteriormente, lembrando que o parâmetro da distribuição chi-quadrado são os graus de liberdade (degrees of freedom - df).\n\n### `pchisq()`\n\nA função pchisq em R é usada para calcular a distribuição acumulada (CDF) da distribuição qui-quadrado ($\\chi^2$). Os principais argumentos da função `pchisq()` são:\n\n-   `q` é o valor da estatística qui-quadrado para o qual você deseja calcular a probabilidade acumulada.\n-   `df` é o número de graus de liberdade da distribuição.\n\nPor padrão a função retorna probabilidade acumulada do valor da estatística ser menor ou igual a `q`. Caso deseje a probabilidade de ser **maior ou igual** a `q` é necessário acrescentar o argumento `lower.tail=FALSE`\n\nSuponha que você tenha uma estatística qui-quadrado de 6 e 2 graus de liberdade e queira calcular a probabilidade acumulada P(x ≤ 6)\n\n\n::: {.cell}\n\n```{.r .cell-code}\npchisq(q = 6, df = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9502129\n```\n\n\n:::\n:::\n\n\nO gráfico abaixo visualiza o uso da função `pchisq(q = 6, df = 2)`\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](14-Distributions_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n### `qchisq()`\n\nA função `qchisq()` é o oposto da `pchisq()`. É usada para calcular o quantil da distribuição qui-quadrado. Em outras palavras, ela encontra o valor `q` tal que a probabilidade acumulada até `q` seja igual a um dado valor de probabilidade `p`. Isso é útil em testes de hipóteses e intervalos de confiança onde se deseja encontrar os pontos críticos da distribuição qui-quadrado.\n\nComo exemplo, usamos a probabilidade 0.9502129, que é o resultado de `pchisq(q = 6, df = 2)` calculado acima. A função devolve então o quantil 6.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqchisq(p = 0.9502129, df = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.999999\n```\n\n\n:::\n:::\n\n\n## Distribuição de Poisson\n\nAs funções para distribuição de Poisson seguem o mesmo padrão das anteriores:\n\n-   `rpois()` cria conjunto randomizado de números numa distribuição de Poisson.\n-   `dpois()` calcula a função de densidade de probabilidade (PDF) da distribuição Poisson. O primeiro argumento é o ponto no eixo x do qual se pretende saber o valor da densidade de probabilidade, o segundo argumento é o parâmetro lambda.\n-   `ppois()` calcula a função de distribuição acumulada (CDF) da distribuição de Poisson, ou seja, calcula a probabilidade de que uma variável aleatória com uma distribuição de Poisson seja menor ou igual a um determinado valor x.\n-   `qpois()` calcula o quantil de uma distribuição de Poisson, ou seja, retorna o valor x tal que a probabilidade acumulada P(X≤x)seja igual a uma probabilidade especificada p.\n\n## Resumo\n\nO R possui essas funções de densidade, densidade cumulativa, quantil e números randomizados para diversas funções. O quadro abaixo resume esse capítulo.\n\n| Distribuição      | PDF (`d`)             | CDF (`p`)             | Quantil (`q`)         | Aleatório (`r`)       |\n|---------------|---------------|---------------|---------------|---------------|\n| Normal            | `dnorm`               | `pnorm`               | `qnorm`               | `rnorm`               |\n| Binomial          | `dbinom`              | `pbinom`              | `qbinom`              | `rbinom`              |\n| Poisson           | `dpois`               | `ppois`               | `qpois`               | `rpois`               |\n| Qui-quadrado      | `dchisq`              | `pchisq`              | `qchisq`              | `rchisq`              |\n| t de Student      | `dt`                  | `pt`                  | `qt`                  | `rt`                  |\n| F                 | `df`                  | `pf`                  | `qf`                  | `rf`                  |\n| Exponencial       | `dexp`                | `pexp`                | `qexp`                | `rexp`                |\n| Gamma             | `dgamma`              | `pgamma`              | `qgamma`              | `rgamma`              |\n| Beta              | `dbeta`               | `pbeta`               | `qbeta`               | `rbeta`               |\n| Geométrica        | `dgeom`               | `pgeom`               | `qgeom`               | `rgeom`               |\n| Hipergeométrica   | `dhyper`              | `phyper`              | `qhyper`              | `rhyper`              |\n| Binomial Negativa | `dnbinom`             | `pnbinom`             | `qnbinom`             | `rnbinom`             |\n| Uniforme          | `dunif`               | `punif`               | `qunif`               | `runif`               |\n| Weibull           | `dweibull`            | `pweibull`            | `qweibull`            | `rweibull`            |\n| Log-normal        | `dlnorm`              | `plnorm`              | `qlnorm`              | `rlnorm`              |\n| Multinomial       | `dmultinom`           | \\-                    | \\-                    | `rmultinom`           |\n| Cauchy            | `dcauchy`             | `pcauchy`             | `qcauchy`             | `rcauchy`             |\n| Beta-Binomial     | `dbetabinom` (VGAM)   | `pbetabinom` (VGAM)   | `qbetabinom` (VGAM)   | `rbetabinom` (VGAM)   |\n| Normal Inversa    | `dinvgauss` (statmod) | `pinvgauss` (statmod) | `qinvgauss` (statmod) | `rinvgauss` (statmod) |\n| Pareto            | `dpareto` (VGAM)      | `ppareto` (VGAM)      | `qpareto` (VGAM)      | `rpareto` (VGAM)      |\n",
    "supporting": [
      "14-Distributions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}